language: cpp

compiler:
  - gcc

dist: bionic

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-9 -y

install:
- "[ $CXX = g++ ] && export CXX=g++-9 || true"

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
