version: 1.0.{build}

image: Visual Studio 2019

platform:
  - x64
configuration:
  - Debug
  - Ship
  
environment:
  VULKAN_SDK: c:\VulkanSDK\1.1.121.2

install:
  - curl -L --silent --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.1.121.2/windows/VulkanSDK-1.1.121.2-Installer.exe?Human=true
  - .\VulkanSDK.exe /S
  - git submodule update --init --recursive

build:
  parallel: true
  verbosity: minimal
  
build_script:
  - mkdir build && cd build
  - cmake -G "Visual Studio 16 2019" -Ax64 ..
  - cmake --build . --config %CONFIGURATION%

notifications:
  - provider: Email
    to:
      - Tyler.Liam7@gmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true